/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 glassy.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/glassy.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.003']} position={[-1.99, 2.66, -1.9]} rotation={[-1.35, -0.5, -1.14]} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Material.001']} position={[1.25, 1.12, -2.62]} rotation={[-1.35, -0.5, -1.14]} scale={1.63} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials['Material.001']} position={[3.88, 2, -2.4]} rotation={[-1.35, -0.5, -1.14]} scale={0.36} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials['Material.002']} position={[1.77, -0.28, -6.22]} rotation={[-1.35, -0.5, -1.14]} scale={1.26} />
      <mesh geometry={nodes.Sphere004.geometry} material={materials['Material.004']} position={[1.52, -1.99, -1.87]} rotation={[-1.35, -0.5, -1.14]} scale={0.56} />
      <mesh geometry={nodes.Sphere005.geometry} material={materials['Material.001']} position={[0.93, 4.22, -1.62]} rotation={[-1.35, -0.5, -1.14]} scale={0.65} />
      <mesh geometry={nodes.Sphere006.geometry} material={materials['Material.001']} position={[2.88, 2.04, 0.32]} rotation={[-1.35, -0.5, -1.14]} scale={0.65} />
      <mesh geometry={nodes.Sphere007.geometry} material={materials['Material.001']} position={[-1.42, -1, -3.06]} rotation={[-1.35, -0.5, -1.14]} scale={0.96} />
      <mesh geometry={nodes.Sphere008.geometry} material={materials['Material.001']} position={[-1.56, 0.94, -3.13]} rotation={[-1.35, -0.5, -1.14]} scale={0.64} />
      <mesh geometry={nodes.Sphere009.geometry} material={materials['Material.001']} position={[-1.22, -0.94, 1.02]} rotation={[-1.35, -0.5, -1.14]} scale={2.23} />
      <mesh geometry={nodes.Sphere010.geometry} material={materials['Material.001']} position={[3.22, 2.65, -5.77]} rotation={[-1.35, -0.5, -1.14]} scale={1.31} />
      <mesh geometry={nodes.Sphere012.geometry} material={materials['Material.001']} position={[2.1, 3.23, -3.84]} rotation={[-1.35, -0.5, -1.14]} scale={0.21} />
      <mesh geometry={nodes.Sphere013.geometry} material={materials['Material.001']} position={[0.71, 0.97, -0.66]} rotation={[-1.35, -0.5, -1.14]} scale={0.21} />
    </group>
  )
}

useGLTF.preload('/glassy.glb')
