/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 painting.glb
Author: alban (https://sketchfab.com/alban)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bob-ross-painting-00a57bbd1c894a7cb9e45ec396a8f660
Title: Bob Ross painting
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Painting(props) {
  const { nodes, materials } = useGLTF('/painting.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/painting.glb')

export default Painting