import Head from "next/head";
import HomePage2 from "components/HomePage2";

import Flower from "components/Flower.jsx";
import Berlin from "../../components/Berlin";

import Title from "../../components/Title";
import Hero from "../../components/Hero";
import Smile from "../../components/Smile";


export default function Home() {
  return (
    
    <div data-scroll-container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Smile/>
     
    <Flower />
      
      <div data-scroll-section>
      <div data-scroll>
          <HomePage2 />
        </div>
      
        
        <div data-scroll>
          <Berlin />
        </div>
        <div className="line-wrap">
        <div className="line"/>
        </div>
        <div data-scroll>
          <Hero />
        </div>
        <div className="line-wrap">
        <div className="line"/>
        </div>
        
        
      </div>
    </div>
  );
}
