import Head from "next/head";
import HomePage2 from "components/HomePage2";

import Flower from "components/Flower.jsx";
import Berlin from "../../components/Berlin";

import Title from "../../components/Title";
import Hero from "../../components/Hero";
import Smile from "../../components/Smile";
import Pictures from "../../components/Pictures";


export default function Home() {
  return (
    
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='wrapper2'>
        <Pictures />
        
    </div>
      
    </div>
  );
}
